# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DumpAndDumper < Formula
  desc ""
  homepage "https://github.com/Thomascogez/dump-and-dumper"
  version "1.0.0"

  on_macos do
    url "https://github.com/Thomascogez/dump-and-dumper/releases/download/v1.0.0/dump-and-dumper_1.0.0_darwin_all.tar.gz"
    sha256 "f97326b0b0c003e546cd1ba8c1ebdbd222d188db46e17a1c135b09b5c23ce49c"

    def install
      bin.install "dump-and-dumper"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Thomascogez/dump-and-dumper/releases/download/v1.0.0/dump-and-dumper_1.0.0_linux_arm64.tar.gz"
      sha256 "09e04d93e059bb39a0de6f21c07f8daa9b4896637ab15bc71128bc0bc091a230"

      def install
        bin.install "dump-and-dumper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Thomascogez/dump-and-dumper/releases/download/v1.0.0/dump-and-dumper_1.0.0_linux_amd64.tar.gz"
      sha256 "957a56502947d9b0697e07e389a3df87ef47bf668f4f08127252ad5794376b48"

      def install
        bin.install "dump-and-dumper"
      end
    end
  end
end
