# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DumpAndDumper < Formula
  desc ""
  homepage "https://github.com/Thomascogez/dump-and-dumper"
  version "1.0.2"

  on_macos do
    url "https://github.com/Thomascogez/dump-and-dumper/releases/download/v1.0.2/dump-and-dumper_1.0.2_darwin_all.tar.gz"
    sha256 "27d68d37e35b91196c237bd32a6e3b117b434498d396b8595a0dd59898344273"

    def install
      bin.install "dump-and-dumper"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Thomascogez/dump-and-dumper/releases/download/v1.0.2/dump-and-dumper_1.0.2_linux_arm64.tar.gz"
      sha256 "3015e873744a5a1b23379061b2821132a985cc0bafbe3c212fa7f89407d6b94b"

      def install
        bin.install "dump-and-dumper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Thomascogez/dump-and-dumper/releases/download/v1.0.2/dump-and-dumper_1.0.2_linux_amd64.tar.gz"
      sha256 "dcf38f54396f2277d271ee480a888a570a4117406e33849718d8fda4e19eb899"

      def install
        bin.install "dump-and-dumper"
      end
    end
  end
end
