# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DumpAndDumper < Formula
  desc ""
  homepage "https://github.com/Thomascogez/dump-and-dumper"
  version "1.0.1"

  on_macos do
    url "https://github.com/Thomascogez/dump-and-dumper/releases/download/v1.0.1/dump-and-dumper_1.0.1_darwin_all.tar.gz"
    sha256 "6d1e401a3306925e1b78f4c93e2ca88902cc0865a97e443923c1ccd5923c33fa"

    def install
      bin.install "dump-and-dumper"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Thomascogez/dump-and-dumper/releases/download/v1.0.1/dump-and-dumper_1.0.1_linux_arm64.tar.gz"
      sha256 "ce8ec10681beff420d5e76f94643b84085d7504cae9adda75d0d5649035644b7"

      def install
        bin.install "dump-and-dumper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Thomascogez/dump-and-dumper/releases/download/v1.0.1/dump-and-dumper_1.0.1_linux_amd64.tar.gz"
      sha256 "010a69f0ce80f685f58306a21f54fd35565e89d59d2a404b894fd964c8a1c3e9"

      def install
        bin.install "dump-and-dumper"
      end
    end
  end
end
